site_name: Aviation Model
theme:
  name: material

nav:
  - Home: 'index.md'
  - Aviation Systems Model: 'aviation.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  