[project]
name = "aviation-model"
version = "0.1.0"
description = "A simple model of the global aviation system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
docs = [
    "mkdocs-material>=9.6.15",
]
